### ISSUE TITLE
informative error message when no permissions to run docker

### ISSUE THREAD

**Issue by igagis** [ChristopherHX/github-actions-act-runner#11]
In case the runner cannot run `docker` due to insufficient permissions there should be an error message saying that in the job log.
Currently it looks like this:
https://github.com/cppfw/utki/runs/3071412644?check_suite_focus=true
i.e.
```
🧪  Matrix: map[codename:buster image_owner:igagis/ labels:[arm docker] os:raspbian package_type:deb]
🚀  Start image=igagis/raspbian:buster
  🐳  docker pull igagis/raspbian:buster
```
which gives no idea of what's happening and doesn't even says `error` word anywhere.

I stumbled upon this in context of this discussion:
https://github.com/ChristopherHX/github-actions-act-runner/discussions/3#discussioncomment-1006108

**Comment by ChristopherHX** [comment]
Act has written the log with the error into a global logger, it should now be redirected to the steps and shown in the log.

**Comment by igagis** [comment]
I will check this later

**Comment by igagis** [comment]
ok, now it looks like this:
https://github.com/cppfw/prorab-extra/runs/3085139556?check_suite_focus=true

it is much better, at least there is information that it couldn't use docker due to insufficient permissions

**Comment by igagis** [comment]
works in release 0.0.3
