### ISSUE TITLE
runner exited due to github went down for a short time

### ISSUE THREAD

**Issue by igagis** [ChristopherHX/github-actions-act-runner#16]
Today one of the runners exited with the following message:
```
{ "message": "GitHub Actions is temporarily unavailable. Please visit https://www.githubstatus.com/ for the status of our services.", "ref": "Ref A: E4830142D0ED4635AEA7E5C1AEB34285 Ref B: HEL03EDGE0207 Ref C: 2021-07-16T12:37:23Z" }
```
So, looks like `github.com` was not reachable for some time.

Perhaps it is better if runner would try to reconnect instead of exiting?

**Comment by igagis** [comment]
though, in case the runner is started as `systemd` service this should not be a problem, as the service can be configured to automatically restart...

**Comment by ChristopherHX** [comment]
My runner was kicked of at the same time, it should retry on http 5xx and sleep some seconds before retry. Currently a retry is only on connection failure.

Needs long term testing to iron out this kind of bugs.

**Comment by ChristopherHX** [comment]
I tried to improve errorhandling of the message loop. Time will tell if it works.

**Comment by igagis** [comment]
Ok, I think this issue can be closed, as it is not easy to check the fix right away
