### ISSUE TITLE
when successfully cnfiguring the runner json is printed

### ISSUE THREAD

**Issue by igagis** [ChristopherHX/github-actions-act-runner#19]
When successfully registering the runner a lot of JSON is printed to the console.
In case of error, the JSON data can be printed to `stderr` for debugging purposes.
In case of success, there is no point in printing all that JSON, as the console output becomes unreadable.

Should just print `success` and return `0` exit code.

**Comment by ChristopherHX** [comment]
done, added wrong issue number to commit

**Comment by igagis** [comment]
if you are sure this is fixed by some of your commits, please close the issue.
I can test and close it only after a new release is made.

**Comment by igagis** [comment]
Ok, I happened to test it with some recent snapshot along when I had to test something else. This seems working, closing the issue.
