### ISSUE TITLE
Failed to recreate Session, waiting 30 sec before retry

### ISSUE THREAD

**Issue by igagis** [ChristopherHX/github-actions-act-runner#20]
today both of my runners went into some strange state, in console they constantly print:
```console
Failed to recreate Session, waiting 30 sec before retry
Failed to recreate Session, waiting 30 sec before retry
Failed to recreate Session, waiting 30 sec before retry
Failed to recreate Session, waiting 30 sec before retry
Failed to recreate Session, waiting 30 sec before retry
```
like every 0.5 seconds another `Failed to recreate Session, waiting 30 sec before retry` line  is printed.

Pressing `Ctrl+C` doesn't help, it just continues printing those lines.

**Comment by igagis** [comment]
new jobs are not picked. Killing and restarting the runner makes it back to normal.

**Comment by ChristopherHX** [comment]
Oh I get why this happend, the authentication wasn't restored while github was connected.
I saw github was down today 11:xx utc. Hard to debug either way.
