### ISSUE TITLE
remove .sh suffix from manager script name

### ISSUE THREAD

**Issue by igagis** [ChristopherHX/github-actions-act-runner#23]
as discussed here
https://github.com/ChristopherHX/github-actions-act-runner/pull/21#discussion_r671754664

it is desirable to remove the `.sh` sufix from the `github-act-runner.sh` script.
The problem here is that there is a `github-act-runner` directory along with that in the `/usr/bin` directory. So, there can be no file with the same name in the same dir.

So, then we also need to rename the `/usr/bin/github-act-runner/` directory to something else. What would be the good name for it? Maybe `/usr/bin/github-act-runner-bin/`?

**Comment by ChristopherHX** [comment]
I would move `/usr/bin/github-act-runner/` to `/usr/share/github-act-runner/bin`.

Then move `github-act-runner.sh` also  to `/usr/share/github-act-runner/bin/`.

Only add a symlink from `/usr/bin/github-act-runner` to `../share/github-act-runner/bin/github-act-runner.sh`.

**Comment by igagis** [comment]
Well, in my understanding it violates FHS: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html
`/usr/share` is for _architecture independent_ *data*, while the runner binary is not a data and is not architecture independent.

I thought about moving everything to `/usr/lib/github-act-runner/` but then it also is not clean, since `/usr/lib` is intended for re-usable stuff by other apps.

Maybe `/opt/github-act-runner/`?

**Comment by igagis** [comment]
Or, actually `/usr/lib` might be ok.
According to https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s06.html:

> On some systems, it may also include internal binaries that are not intended to be executed directly by users or shell scripts.

**Comment by ChristopherHX** [comment]
I forget llvm uses lib not share on ubuntu 20.04
```
lrwxrwxrwx 1 root root 24 Mar 20  2020 /usr/bin/clang -> ../lib/llvm-10/bin/clang
```

**Comment by igagis** [comment]
Then `/usr/lib/github-act-runner/` is the solution? I can make the change.

**Comment by ChristopherHX** [comment]
Yes for me this is a good solution.

**Comment by igagis** [comment]
I'll make a PR then
