### ISSUE TITLE
The runner does not respect cancelling the job

### ISSUE THREAD

**Issue by igagis** [ChristopherHX/github-actions-act-runner#8]
When workflow is cancelled via github actions web ui all the jobs are cancelled except those run by this runner. Those jobs continue performing all the remaining steps until finish.

**Comment by igagis** [comment]
with the latest snapshot cancelling works. But looks like it still finishes the current step and only then cancels the job.
I'm not sure, but I think standard github runner sends some terminate signals to active processes so that current step is interrupted beforehand. Not sure how easy it is to implement in `act-runner`. It is already good that it works at least as currently.

Also, when stopping the job due to user cancel, need to add a message to the log saying "The job was cancelled", latest snapshot does not do that.

**Comment by ChristopherHX** [comment]
I guess cancellation need to be improved inside of act, ctrl+c while running act has similar behavior.

Adding "The job was cancelled" to the log should be possible.
